### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'click')

### ISSUE THREAD

**Issue by CRGer** [Zefau/ioBroker.jarvis#1170]
jarvis ist wegen eines Fehlers abgestürzt

TypeError: Cannot read properties of null (reading 'click')
    at Object.cb (http://192.168.52.28:8082/jarvis/static/js/main.1a61ba6f.chunk.js:1:119420)
    at callback (http://192.168.52.28:8082/jarvis/static/js/8.1e7f7555.chunk.js:1:1371)
    at http://192.168.52.28:8082/jarvis/static/js/6.2d6ff320.chunk.js:2:96882
    at n.value (http://192.168.52.28:8082/jarvis/static/js/6.2d6ff320.chunk.js:2:94176)
    at cs (http://192.168.52.28:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1048007)
    at xl (http://192.168.52.28:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1065665)
    at t.unstable_runWithPriority (http://192.168.52.28:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1085033)
    at qi (http://192.168.52.28:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1009340)
    at wl (http://192.168.52.28:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1062328)
    at sl (http://192.168.52.28:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1058459)

**Comment by Zefau** [comment]
Bitte auf v3 gehen
