### ISSUE TITLE
Jarvis bei Einrichtung abgestürzt

### ISSUE THREAD

**Issue by mitmi1811** [Zefau/ioBroker.jarvis#1579]
Moin, bei mir ist Jarvis kurz nach der Installation bei der Einrichtung abgestürzt, ich habe bei einer ersten Installation die automatische Konfoguration laufen lassen, da ist das auch schon passiert. Jetzt nach einer Neuinstallation den gesamten Adapters ist Jarvis mitr folgendem Fehler abgestürzt:

jarvis ist wegen eines Fehlers abgestürzt
Bitte screenshote diese Seite und melde es dem Entwickler (via Github oder ioBroker Forum)

TypeError: Cannot read properties of null (reading 'click')
TypeError: Cannot read properties of null (reading 'click')
    at Object.cb (http://192.168.178.93:8082/jarvis/static/js/main.1a61ba6f.chunk.js:1:119420)
    at callback (http://192.168.178.93:8082/jarvis/static/js/8.1e7f7555.chunk.js:1:1371)
    at http://192.168.178.93:8082/jarvis/static/js/6.2d6ff320.chunk.js:2:96882
    at n.value (http://192.168.178.93:8082/jarvis/static/js/6.2d6ff320.chunk.js:2:94176)
    at cs (http://192.168.178.93:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1048007)
    at xl (http://192.168.178.93:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1065665)
    at t.unstable_runWithPriority (http://192.168.178.93:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1085033)
    at qi (http://192.168.178.93:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1009340)
    at wl (http://192.168.178.93:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1062328)
    at sl (http://192.168.178.93:8082/jarvis/static/js/11.7df4888c.chunk.js:2:1058459)

**Comment by mitmi1811** [comment]
Nach einigen Minuten war Jarvis wieder aufrufbar

**Comment by Zefau** [comment]
Bitte auf v3 gehen
