### ISSUE TITLE
Absturz: Anwenderfehler beim Hinzufügen einer JSON-Tabelle statt eines einzelnen Werts (Geräte)

### ISSUE THREAD

**Issue by TobiasHaPunkt** [Zefau/ioBroker.jarvis#1642]
**Prerequisites / Voraussetzungen**
jarvis 2.2.1 - Browserunabhängig

**Describe the bug / Beschreibe den Fehler**
Leider habe ich beim Anlegen eines neuen Geräts nicht aufgepasst und eine JSON-Tabelle als Variable hinzugefügt. Seither läuft die Visualisierung auf den hier dargestellten Fehler. Das Jarvis-Backup habe ich wiederhergestellt (Einstellungen -> Geräte -> altes Datum -> Restore -> Adapterneustart -> Seite ohne Cache neu laden) allerdings ohne Erfolg. Kann mir hier bitte jemand beim Wiederherstellen weiterhelfen?

**Browser-Consolenausgabe (Opera):**
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at So (react-dom.production.min.js:139:47)
    at react-dom.production.min.js:149:278
    at La (react-dom.production.min.js:173:103)
    at _s (react-dom.production.min.js:265:156)
    at bl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at sl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at qi (react-dom.production.min.js:122:325)

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at So (react-dom.production.min.js:139:47)
    at react-dom.production.min.js:149:278
    at La (react-dom.production.min.js:173:103)
    at _s (react-dom.production.min.js:265:156)
    at bl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at sl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at qi (react-dom.production.min.js:122:325) {componentStack: '\n    in span\n    in ForwardRef\n    in ForwardRef\n …wardRef\n    in Unknown\n    in s\n    in ForwardRef'}

**Screenshots**
![image](https://user-images.githubusercontent.com/101196214/157259786-1a31e70a-fed8-4cc0-9a2d-37ba2f64ba04.png)

____

**Comment by Zefau** [comment]
Da scheint es die Installation zerschossen zu haben.

Ich empfehle dir grundsätzlich auf die v3 zu wechseln. Wenn du auf v2 bleiben willst, dann installiere den Adapter nochmal komplett neu inkl. Adapter Upload und ioBroker restart.

**Comment by TobiasHaPunkt** [comment]
Vielen Dank für die Info. Ich hab nun auf v3 aktualisiert und die Daten sind alle noch da. Danke :)
