### ISSUE TITLE
Klick auf Tricolon -> Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1824]
Nur das Klicken auf das Tricolon verursacht den Fehler. Der TAB wird gelöscht.

![image](https://user-images.githubusercontent.com/84818934/186650483-20e0eaf7-87b4-40e6-aa45-c7f75ed7ca32.png)

```
TypeError: Cannot convert object to primitive value
    at Array.join (<anonymous>)
    at Log._message (index-693ab822.js:37:924)
    at Log.dev (index-693ab822.js:39:141)
    at Proxy.p (index-ab7f008e.js:1:20246)
    at ref (index-ab7f008e.js:1:26908)
    at callWithErrorHandling (index-693ab822.js:4:791)
    at setRef (index-693ab822.js:4:39763)
    at I (index-693ab822.js:4:44472)
    at he (index-693ab822.js:4:50901)
    at be (index-693ab822.js:4:50339)
    at z (index-693ab822.js:4:46517)
    at $ (index-693ab822.js:4:44972)
    at I (index-693ab822.js:4:44351)
    at ReactiveEffect.ce [as fn] (index-693ab822.js:4:48870)
    at ReactiveEffect.run (index-693ab822.js:1:7384)
    at E.update (index-693ab822.js:4:49829)
    at ge (index-693ab822.js:4:48509)
    at X (index-693ab822.js:4:48064)
    at I (index-693ab822.js:4:44381)
    at he (index-693ab822.js:4:50901)
    at be (index-693ab822.js:4:50339)
    at z (index-693ab822.js:4:46517)
    at $ (index-693ab822.js:4:44972)
    at I (index-693ab822.js:4:44351)
    at ReactiveEffect.ce [as fn] (index-693ab822.js:4:48870)
    at ReactiveEffect.run (index-693ab822.js:1:7384)
    at E.update (index-693ab822.js:4:49829)
    at ge (index-693ab822.js:4:48509)
    at X (index-693ab822.js:4:48064)
    at I (index-693ab822.js:4:44381)
    at ReactiveEffect.ce [as fn] (index-693ab822.js:4:48870)
    at ReactiveEffect.run (index-693ab822.js:1:7384)
    at E.update (index-693ab822.js:4:49829)
    at ge (index-693ab822.js:4:48509)
    at X (index-693ab822.js:4:48064)
    at I (index-693ab822.js:4:44381)
    at he (index-693ab822.js:4:50901)
    at be (index-693ab822.js:4:50339)
    at Object.process (index-693ab822.js:4:56002)
    at I (index-693ab822.js:4:44425)
    at he (index-693ab822.js:4:50901)
    at be (index-693ab822.js:4:50339)
    at Z (index-693ab822.js:4:47917)
    at I (index-693ab822.js:4:44307)
    at ReactiveEffect.ce [as fn] (index-693ab822.js:4:48870)
    at ReactiveEffect.run (index-693ab822.js:1:7384)
    at E.update (index-693ab822.js:4:49829)
    at ge (index-693ab822.js:4:48509)
    at X (index-693ab822.js:4:48064)
    at I (index-693ab822.js:4:44381)
```

**Comment by Zefau** [comment]
Ist das noch aktuell?

**Comment by mcuiobroker** [comment]
Zurzeit mit Fieber beschäftigt. Dauert ein paar Tage.

**Comment by mcuiobroker** [comment]
Nein.
