### ISSUE TITLE
v3.1.0-alpha.35 AdapterStatus Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1830]
![image](https://user-images.githubusercontent.com/84818934/186979324-3b7dc154-c42b-4396-9e3e-1ec8a15d2b4b.png)

`
TypeError: I.locale.substr is not a function
    at ReactiveEffect.fn (AdapterStatus-8c7d8a72.js:1:1644)
    at ReactiveEffect.run (index-693ab822.js:1:7384)
    at get value [as value] (index-693ab822.js:1:19433)
    at unref (index-693ab822.js:1:18100)
    at Object.get (index-693ab822.js:1:18150)
    at Object.get (index-693ab822.js:4:28448)
    at AdapterStatus-8c7d8a72.js:1:3232
    at o (index-693ab822.js:4:6210)
    at hSlot (index-693ab822.js:4:111083)
    at Proxy.<anonymous> (index-693ab822.js:4:114592)
`

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.37` passen

**Comment by mcuiobroker** [comment]
Keine Meldung mehr. Danke.
