### ISSUE TITLE
Paypal Login Pro Account funktioniert nicht

### ISSUE THREAD

**Issue by firechhe** [Zefau/ioBroker.jarvis#1947]
**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? v3.0.13

**Describe the bug / Beschreibe den Fehler**
Der Paypal Login wird nicht akzeptiert. Nach dem Login steht weiterhin der "Login with Paypal" Button da. Ein Kauf des Pro Accounts ist nicht möglich.

Gibt es eine Alternative einen Pro Account zu erwerben?

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Probier mal bitte die V3.1-alpha.

Welchen Browser benutzt du? Hast du pihole oder andere AdBlocker im Einsatz?

**Comment by firechhe** [comment]
Ich nutze Firefox 105.0.1
uBlock ist installiert, habe ich aber schon deaktiviert. Google Chrome funktioniert ebenfalls nicht.

Im PopUp Fenster erscheint folgende Meldung:
![01](https://user-images.githubusercontent.com/43295016/193543447-00141f4e-a6cf-4a96-b67a-3bdd153dcb9b.jpg)

Wie kann ich die V3.1 alpha installieren? Habe die latest Repository aktiviert, dort erscheint sie nicht.

**Comment by Zefau** [comment]
Direkt von GitHub

**Comment by firechhe** [comment]
Entschuldige, ich habe noch nie eine Alpha installiert. Reicht es aus, wenn ich einen Adapter per URL installiere und diese URL nehme?:

https://github.com/Zefau/ioBroker.jarvis

**Comment by firechhe** [comment]
Die Installation mit diesem Link:
https://github.com/Zefau/ioBroker.jarvis/tree/545f3134a75bd6c9ed48a1a3e758ed175654d186

läuft nicht durch.
![02](https://user-images.githubusercontent.com/43295016/193547693-388f1bf8-6649-46a0-924f-cc8f907747f8.jpg)

**Comment by Zefau** [comment]
via Katze und dann https://github.com/Zefau/ioBroker.jarvis

**Comment by firechhe** [comment]
Auch mit der Version v3.1.0-alpha.54 funktioniert es nicht.
Nach Login werde ich wieder auf die Jarvis Seite weitergeleitet und bin nicht eingeloggt.

**Comment by mcuiobroker** [comment]
Dann kannst du es noch mit v3.0.11 versuchen. Dazu auf der console `iob upgrade jarvis@3.0.11` eingeben.

**Comment by firechhe** [comment]
Auch mit v3.0.11 existiert das Problem unverändert.

**Comment by Bernd9000** [comment]
Ich hab wohl auch das Problem..
Auch mit Pro Account kann ich mich in jarvis nicht mehr bei Paypal anmelden (v3.0.13)
Bei der v3.1.0-alpha.54 kommt ein javascript error


![Unbenannt](https://user-images.githubusercontent.com/77005685/193909788-420141da-98ff-404b-9d26-02f639ab294d.jpg)
![Unbenann2t](https://user-images.githubusercontent.com/77005685/193911801-37294336-bb4e-46a4-84e5-314d984794d5.jpg)

**Comment by Bernd9000** [comment]
Nachtrag:
Mit der v3.0.13 und dem **Edge Browser** wird mir sofort die Benutzer ID und die Rechnung angezeigt.
Bei der v3.1.0-alpha.54 funktioniert es auch nicht mit dem Edge Browser

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.0-alpha.55`

**Comment by mcuiobroker** [comment]
Alles rechts oder links untereinander besser?
![image](https://user-images.githubusercontent.com/84818934/194670080-1e26f0d1-1d22-44a7-9ace-6f05969d53fd.png)

**Comment by Bernd9000** [comment]
v3.1.0-alpha.55
Mit Get Invoices wird mir das so wie bei mcuiobroker angezeigt, die Daten werden gefunden.
Dann klick auf set Licence aber......
Auf der linken Seite wird es nach wie vor nicht angezeigt.

v3.0.13
Da hab ich ja geschrieben das es mit dem Edge Browser funktioniert.
Gehe ich hier im LAN an einem anderen Rechner mit identischer Edge Browser Version funktioniert es wieder nicht.

**Comment by mcuiobroker** [comment]
@Bernd9000 Bzgl. v3.0.13, da muss erst noch ne neue Version kommen.

**Comment by Bernd9000** [comment]
@mcuiobroker 
Okay, und wird bei Dir in der alpha Version auf der linken Seite (wie bei 3.0.13) der Kauf angezeigt ?

**Comment by mcuiobroker** [comment]
Eben nicht mehr links (momentan) sondern, jetzt rechts in der Anzeige Get Invoice, nehme ich an.

**Comment by mcuiobroker** [comment]
@Zefau Daten von Get Invoice werden nicht gespeichert. Einmal aus der Konfig raus und sie sind weg.
Kann man nicht die Daten aus der vorhandenen PRO-License (jarvis.0.info.pro) lesen und die daten dort direkt eintragen und automatisch die Invoice holen?

**Comment by Zefau** [comment]
bitte nochmal mit `v3.1.0-alpha.56` prüfen

**Comment by Bernd9000** [comment]
Lizenz wird jetzt bei einem vorhandenen Pro Account sofort angezeigt.

**Comment by Bernd9000** [comment]
`v3.0.14` funktioniert auch wieder :-)

**Comment by Zefau** [comment]
Jetzt ist die Frage, ob der Erwerb der Pro-Lizenz auch wieder funktioniert.
Entweder klappt das nicht oder es hat bisher noch niemand versucht ;-)

**Comment by awsmfab** [comment]
Scheint noch nicht zu funktionieren wenn keine Lizenz vorhanden ist. (v3.0.14)

Folgende Fehler kommen beim Aufruf von `/jarvis/index.html#/configuration/account` (Die Seite bleibt leer):
```
7.f1547bae.js:1 AccountPage setup()
app.7f6a86c2.js:1 Global Cannot read properties of null (reading 'subscriber') TypeError: Cannot read properties of null (reading 'subscriber')
    at setup (7.f1547bae.js:1:16737)
    at vendor.3ed67ef3.js:170:34265
    at vendor.3ed67ef3.js:170:32626
    at ve (vendor.3ed67ef3.js:170:32130)
    at n (vendor.3ed67ef3.js:170:32607)
    at e.data (vendor.3ed67ef3.js:170:32441)
    at hi (vendor.3ed67ef3.js:112:33035)
    at ui (vendor.3ed67ef3.js:112:32835)
    at li (vendor.3ed67ef3.js:112:32456)
    at Ai.t._init (vendor.3ed67ef3.js:112:34706)
Global Cannot read properties of undefined (reading 'SupportByBuying') TypeError: Cannot read properties of undefined (reading 'SupportByBuying')
    at a.n (7.f1547bae.js:1:12475)
    at vendor.3ed67ef3.js:170:32378
    at ve (vendor.3ed67ef3.js:170:32130)
    at e.render (vendor.3ed67ef3.js:170:32349)
    at An.t._render (vendor.3ed67ef3.js:112:23978)
    at a.i (vendor.3ed67ef3.js:112:28019)
    at oi.get (vendor.3ed67ef3.js:112:30904)
    at new oi (vendor.3ed67ef3.js:112:30822)
    at Ln (vendor.3ed67ef3.js:112:28033)
    at Ci.$mount (vendor.3ed67ef3.js:112:71635)
```

**Comment by Zefau** [comment]
Im latest ist bereits 3.0.15

**Comment by awsmfab** [comment]
Einmal komplett durchgetestet in 3.0.15, läuft.

**Comment by Pat-u** [comment]
Kann auch bestätigen, dass es im 3.0.15 funktioniert
