### ISSUE TITLE
jarvis-oberfläche startet nicht

### ISSUE THREAD

**Issue by markTrier** [Zefau/ioBroker.jarvis#2013]
jarvis Version 3.0.15

Beim Starten der Konsole folgende Fehlermeldung:
URIError: Failed to decode param '%web_protocol%://192.168.178.30:8082/jarvis/index.html'
    at decodeURIComponent (<anonymous>)
    at decode_param (/opt/iobroker/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/opt/iobroker/node_modules/express/lib/router/layer.js:148:15)
    at matchLayer (/opt/iobroker/node_modules/express/lib/router/index.js:585:18)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:226:15)
    at compression (/opt/iobroker/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:328:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:346:12)

Was tun??

**Comment by mcuiobroker** [comment]
Direkt nach dem Update?

**Comment by markTrier** [comment]
Ich habe ein Update von iobroker auf 4.0.23 gemacht. Danach ging es nicht mehr. Ich nehme an, dass derweil alle Adapter automatisch mit geupdatet wurden. So genau kann ich das aber nicht sagen.

**Comment by mcuiobroker** [comment]
Gibt es denn im Log irgendwelche Hinweise? Errors?
- web-Instanz neu gestartet?
- jarvis neu gestartet?
- cache vom Browser gelöscht?

**Comment by markTrier** [comment]
Die Web-Instanz war's. Je länger man einen Fehler wiederholt, umso blinder wird man. Vielen DANK!

**Comment by mcuiobroker** [comment]
Bitte schließen. Danke.
