### ISSUE TITLE
jarvis startet nach update von 3.0.15 auf 3.1.2 nicht mehr 

### ISSUE THREAD

**Issue by PeHasl** [Zefau/ioBroker.jarvis#2419]
Hallo,

nachdem ich das Update von Jarvis 3.0.15 auf 3.1.2 durchgeführt habe, startet Jarvis leider nicht mehr. 

Im Log finde ich eine 'uncaught exception: Cannot read properties of null'. Nach einigen Versuchen wird der Adapter dann gestoppt (Restart loop detected). 

Ich hänge hier mal einen Auszug aus dem Log an:

----------------------------------------------------------------------------------------------------------------------------------

2023-08-22 07:18:03.758  - info: host.hd-vm-ubuntu-01 "system.adapter.jarvis.0" enabled
2023-08-22 07:18:03.931  - info: host.hd-vm-ubuntu-01 instance system.adapter.jarvis.0 started with pid 4550
2023-08-22 07:18:31.602  - error: jarvis.0 (4550) uncaught exception: Cannot read properties of null (reading 'findIndex')
2023-08-22 07:18:31.605  - error: jarvis.0 (4550) TypeError: Cannot read properties of null (reading 'findIndex')
at /opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:7279
at Array.forEach ()
at /opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:7083
at Array.forEach ()
at Immediate. (/opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:6637)
at process.processImmediate (node:internal/timers:478:21)
2023-08-22 07:18:31.605  - error: jarvis.0 (4550) Cannot read properties of null (reading 'findIndex')
2023-08-22 07:18:32.327  - warn: jarvis.0 (4550) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-22 07:18:32.935  - error: host.hd-vm-ubuntu-01 instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-22 07:18:32.936  - info: host.hd-vm-ubuntu-01 Restart adapter system.adapter.jarvis.0 because enabled
2023-08-22 07:19:03.089  - info: host.hd-vm-ubuntu-01 instance system.adapter.jarvis.0 started with pid 4565
2023-08-22 07:19:31.402  - error: jarvis.0 (4565) uncaught exception: Cannot read properties of null (reading 'findIndex')
2023-08-22 07:19:31.406  - error: jarvis.0 (4565) TypeError: Cannot read properties of null (reading 'findIndex')
at /opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:7279
at Array.forEach ()
at /opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:7083
at Array.forEach ()
at Immediate. (/opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:6637)
at process.processImmediate (node:internal/timers:478:21)
2023-08-22 07:19:31.406  - error: jarvis.0 (4565) Cannot read properties of null (reading 'findIndex')
2023-08-22 07:19:31.413  - warn: jarvis.0 (4565) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-22 07:19:32.021  - error: host.hd-vm-ubuntu-01 instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-22 07:19:32.021  - info: host.hd-vm-ubuntu-01 Restart adapter system.adapter.jarvis.0 because enabled
2023-08-22 07:20:02.663  - info: host.hd-vm-ubuntu-01 instance system.adapter.jarvis.0 started with pid 4583
2023-08-22 07:20:31.615  - error: jarvis.0 (4583) uncaught exception: Cannot read properties of null (reading 'findIndex')
2023-08-22 07:20:31.619  - error: jarvis.0 (4583) TypeError: Cannot read properties of null (reading 'findIndex')
at /opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:7279
at Array.forEach ()
at /opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:7083
at Array.forEach ()
at Immediate. (/opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:6637)
at process.processImmediate (node:internal/timers:478:21)
2023-08-22 07:20:31.620  - error: jarvis.0 (4583) Cannot read properties of null (reading 'findIndex')
2023-08-22 07:20:31.629  - warn: jarvis.0 (4583) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-22 07:20:32.277  - error: host.hd-vm-ubuntu-01 instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-22 07:20:32.278  - info: host.hd-vm-ubuntu-01 Restart adapter system.adapter.jarvis.0 because enabled
2023-08-22 07:20:32.278  - warn: host.hd-vm-ubuntu-01 Do not restart adapter system.adapter.jarvis.0 because restart loop detected

----------------------------------------------------------------------------------------------------------------------------------

Danke im Voraus für die Unterstützung!

**Comment by mcuiobroker** [comment]
Zeig mal bitte die DPs Devices, widgets. Nur in der Objekt Übersicht.

**Comment by PeHasl** [comment]
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/89119260/6a0dbde4-dd11-4bd9-9a06-0b114f29fa50)

**Comment by mcuiobroker** [comment]
Bisschen mehr nach Version 3?

**Comment by PeHasl** [comment]
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/89119260/222cf221-464a-431a-890e-57f33504fb73)

**Comment by mcuiobroker** [comment]
Wenn man jarvis Frontend startet welche Fehlermeldung sieht man mit F12?

**Comment by PeHasl** [comment]
Hm, schwierig. Der Adapter beendet sich ja nach kurzer Zeit wieder. Die einzige Meldung, die ich mit F12 finden kann, ist diese da:

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://192.168.0.131:8400/jarvis-socket/?EIO=4&transport=polling&t=OeUXrCj. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

**Comment by mcuiobroker** [comment]
Starte mal jarvis aus der Instanz Übersicht.

**Comment by PeHasl** [comment]
Hab ich schon so gemacht.

**Comment by mcuiobroker** [comment]
Web Adapter neugestartet?

**Comment by PeHasl** [comment]
> Web Adapter neugestartet? Ist Web.0?

Ja und ja. Leider das gleiche Verhalten.

**Comment by mcuiobroker** [comment]
Ich habe zur Zeit kein System, um es nachzudenken. 
Wieder auf 3.015 zurück?
```
iob upgrade jarvis@3.0.15
```

**Comment by PeHasl** [comment]
Ja kein Thema. Ich gehe vorerst wieder auf 3.0.15.
Danke!

**Comment by mcuiobroker** [comment]
Welche nodejs hast du auf dem System? 16.20.x 
iobroker Version? 4.0.24

**Comment by PeHasl** [comment]
nodejs 18.17.1
iobroker 5.0.12
läuft auf einer Virtuellen Maschine mit Ubuntu 22.04.3 LTS
