### ISSUE TITLE
3.2.0-alpha.21 - TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by fprobst170** [Zefau/ioBroker.jarvis#2493]
Jarvis stürzt nach einiger Zeit ab.

folgende Einträge im Eventlog

2023-12-20 15:04:25.077  - [31merror[39m: jarvis.0 (22535) uncaught exception: Cannot read properties of null (reading 'ts')
2023-12-20 15:04:25.081  - [31merror[39m: jarvis.0 (22535) TypeError: Cannot read properties of null (reading 'ts')
    at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.server.js:1:1979)
    at Adapter.emit (node:events:529:35)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5385:53)
    at process.processImmediate (node:internal/timers:476:21)
2023-12-20 15:04:25.086  - [31merror[39m: jarvis.0 (22535) Cannot read properties of null (reading 'ts')
2023-12-20 15:04:25.104  - [32minfo[39m: jarvis.0 (22535) Adapter stopped und unloaded.
2023-12-20 15:04:25.105  - [32minfo[39m: jarvis.0 (22535) terminating
2023-12-20 15:04:25.106  - [33mwarn[39m: jarvis.0 (22535) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-20 15:04:25.739  - [31merror[39m: host.ioBroker01 instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-12-20 15:04:25.739  - [32minfo[39m: host.ioBroker01 Restart adapter system.adapter.jarvis.0 because enabled

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.22` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.22` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by fprobst170** [comment]
Danke, funktioniert nun ohne Abstürze.
