### ISSUE TITLE
[v3.2.0-alpha.26] Jarvis sehr langsam

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2500]
Hej,

irgendwie schmiert regelmäßig mein Jarvis ab und ist sehr langsam. Liegt das an der aktuellen Version? (v3.2.0-alpha.26)
Der aktuelle Reload lässt die Seite schwarz bzw. weiß und lädt nicht mehr Jarvis. Wie kann ich euch mehr Infos geben?

ich hatte auch vor einigen Tagen das der Adapter ganz abgeraucht ist und iobroker gemeldet hat das der ihn beendet da mehrere automatische Neustarts nichts gebracht haben.

VG

**Comment by Zefau** [comment]
Fehler / Warnungen entweder direkt im ioBroker Log oder bei offenem jarvis in der Browser-Konsole (via F12).

**Comment by Mephisto090** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/c98757b9-b8b9-4b4e-92f7-a76f20d89df4)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/f0f2bec3-c856-408e-a1b2-c6c3624ee74f)

So? :)

**Comment by Mephisto090** [comment]
```
jarvis.0
2023-12-28 17:22:23.281	info	Server has 1 connected clients.

jarvis.0
2023-12-28 17:22:23.280	info	Client with ip 192.168.178.72 (using Android Browser) connected.

jarvis.0
2023-12-28 17:22:20.514	info	State value to set for "jarvis.0.settings.secureConfigurationType" has to be type "boolean" but received type "string"

jarvis.0
2023-12-28 17:22:19.488	info	Found Backups for devices.

jarvis.0
2023-12-28 17:22:19.470	info	Found Backups for widgets.

jarvis.0
2023-12-28 17:22:19.459	info	Found Backups for styles.

jarvis.0
2023-12-28 17:22:19.458	info	Found Backups for settings.

jarvis.0
2023-12-28 17:22:19.456	info	Found Backups for layout.

jarvis.0
2023-12-28 17:22:19.452	info	Connection: WebSocket opened on port 8400 using http...

jarvis.0
2023-12-28 17:22:19.413	info	No Backup found for scripts, thus backing up initially.

jarvis.0
2023-12-28 17:22:19.347	info	starting. Version 3.2.0-alpha.26 (non-npm: Zefau/ioBroker.jarvis) in /opt/iobroker/node_modules/iobroker.jarvis, node: v18.19.0, js-controller: 5.0.16

jarvis.0
2023-12-28 17:21:46.918	info	terminating

jarvis.0
2023-12-28 17:21:46.415	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

jarvis.0
2023-12-28 17:21:46.414	info	terminating

jarvis.0
2023-12-28 17:21:46.412	info	Adapter stopped und unloaded.

jarvis.0
2023-12-28 17:21:46.403	error	Converting circular structure to JSON --> starting at object with constructor 'Timeout' | property '_idlePrev' -> object with constructor 'TimersList' --- property '_idleNext' closes the circle

jarvis.0
2023-12-28 17:21:46.403	error	TypeError: Converting circular structure to JSON --> starting at object with constructor 'Timeout' | property '_idlePrev' -> object with constructor 'TimersList' --- property '_idleNext' closes the circle at JSON.stringify (<anonymous>) at JarvisServer.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.min.js:1:6071) at JarvisServer.emit (node:events:517:28) at /opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.server.client.js:1:562

jarvis.0
2023-12-28 17:21:46.402	error	unhandled promise rejection: Converting circular structure to JSON --> starting at object with constructor 'Timeout' | property '_idlePrev' -> object with constructor 'TimersList' --- property '_idleNext' closes the circle

jarvis.0
2023-12-28 17:21:46.401	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

jarvis.0
2023-12-28 17:21:46.396	info	Server has 1 connected clients.

jarvis.0
2023-12-28 17:21:46.382	info	Client with ip 192.168.178.59 disconnected.

jarvis.0
2023-12-28 17:19:45.266	info	Server has 2 connected clients.

jarvis.0
2023-12-28 17:19:45.259	info	Client with ip 192.168.178.72 (using Android Browser) connected.

jarvis.0
2023-12-28 17:15:44.438	info	Backup devices..

jarvis.0
2023-12-28 17:15:23.744	info	Server has 1 connected clients.

jarvis.0
2023-12-28 17:15:23.743	info	Client with ip 192.168.178.59 (using Chrome) connected.

jarvis.0
2023-12-28 17:15:22.971	info	Server has 0 connected clients.

jarvis.0
2023-12-28 17:15:22.962	info	Client with ip 192.168.178.59 disconnected.

jarvis.0
2023-12-28 17:15:19.351	info	Backup devices..

jarvis.0
2023-12-28 17:14:45.236	info	Server has 1 connected clients.

jarvis.0
2023-12-28 17:14:45.235	info	Client with ip 192.168.178.59 (using Chrome) connected.

jarvis.0
2023-12-28 17:14:44.394	info	Server has 0 connected clients.

jarvis.0
2023-12-28 17:14:44.383	info	Client with ip 192.168.178.59 disconnected.

jarvis.0
2023-12-28 17:14:39.758	info	Backup settings..

jarvis.0
2023-12-28 17:14:39.756	info	Backup settings..

jarvis.0
2023-12-28 17:14:39.691	info	Backup devices..
```

**Comment by Zefau** [comment]
ok, sollte mit dem nächsten Release behoben sein

**Comment by Mephisto090** [comment]
Alles klar das ging flott :D

**Comment by Mephisto090** [comment]
kommt das Update heute noch oder soll ich zurück auf eine bestimmte Version?

**Comment by Zefau** [comment]
> Alles klar das ging flott :D Wo lag das Problem, wenn ich fragen darf?

In den Alpha-Versionen baue ich in der Regel viel um, daher kommt es immer zu vielen Fehlern. Im Falle von v3.2 insbesondere die Umstellung von Socket-io auf WebSocket.

> kommt das Update heute noch oder soll ich zurück auf eine bestimmte Version?

Sicherlich noch heute, spätestens morgen. Kannst aber sonst erstmal zurück gehen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.27` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.27` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
Die Fehlermeldung `Converting circular structure to JSON --> starting at object with constructor 'Timeout' | property '_idlePrev' -> object with constructor 'TimersList' --- property '_idleNext' closes the circle` bekommst du im ioBroker Log nicht mehr, richtig?

**Comment by Mephisto090** [comment]
Nein denke nicht oder?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/5263be1d-e017-4347-a8b3-477ad8fb96a4)
