### ISSUE TITLE
[v3.2.0-alpha.26] Geräteliste plötzlich leer

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2501]
Nach Aktualisierung auf .26 ist die Geräteliste plötzlich leer. In den Objekten im ioBroker ist aber unter devices noch alles drin. Alle Widgets mit Geräten laden auch nicht mehr.

**Comment by Zefau** [comment]
Fehler in der Browser Konsole via F12?

**Comment by intruder7777** [comment]
`index-7c5674b0.js:5  TypeError: Cannot read properties of undefined (reading 'id')
    at Proxy._sfc_render$H (index-7c5674b0.js:1661:13188)
    at renderComponentRoot (index-7c5674b0.js:1:27134)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74578)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at oe (index-7c5674b0.js:1:72742)
    at F (index-7c5674b0.js:1:69030)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:73971)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at callWithErrorHandling (index-7c5674b0.js:1:21605)
    at flushJobs (index-7c5674b0.js:1:24321)
(anonymous) @ index-7c5674b0.js:5
index-7c5674b0.js:5  TypeError: Cannot read properties of undefined (reading '7c976a6c-06f3-4d2b-bf61-a908ebc2a1d1')
    at Devices.getDevice (index-7c5674b0.js:114:458208)
    at Devices.get (index-7c5674b0.js:114:458143)
    at setup (index-7c5674b0.js:1909:210125)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at setupStatefulComponent (index-7c5674b0.js:1:90664)
    at setupComponent (index-7c5674b0.js:1:90317)
    at ae (index-7c5674b0.js:1:73235)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
(anonymous) @ index-7c5674b0.js:5
index-7c5674b0.js:5  TypeError: Cannot read properties of undefined (reading '750ad506-375a-4404-a017-4d1e63a32555')
    at Devices.getDevice (index-7c5674b0.js:114:458208)
    at Devices.get (index-7c5674b0.js:114:458143)
    at watch.immediate (index-7c5674b0.js:1661:10308)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at callWithAsyncErrorHandling (index-7c5674b0.js:1:21719)
    at H (index-7c5674b0.js:1:36079)
    at doWatch (index-7c5674b0.js:1:36387)
    at watch (index-7c5674b0.js:1:34937)
    at setup (index-7c5674b0.js:1661:9173)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at setupStatefulComponent (index-7c5674b0.js:1:90664)
    at setupComponent (index-7c5674b0.js:1:90317)
    at ae (index-7c5674b0.js:1:73235)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
(anonymous) @ index-7c5674b0.js:5
index-7c5674b0.js:5  TypeError: Cannot read properties of undefined (reading '2bebf121-d7ab-430e-aed6-9e02017b6a3f')
    at Devices.getDevice (index-7c5674b0.js:114:458208)
    at Devices.get (index-7c5674b0.js:114:458143)
    at watch.immediate (index-7c5674b0.js:1661:10308)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at callWithAsyncErrorHandling (index-7c5674b0.js:1:21719)
    at H (index-7c5674b0.js:1:36079)
    at doWatch (index-7c5674b0.js:1:36387)
    at watch (index-7c5674b0.js:1:34937)
    at setup (index-7c5674b0.js:1661:9173)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at setupStatefulComponent (index-7c5674b0.js:1:90664)
    at setupComponent (index-7c5674b0.js:1:90317)
    at ae (index-7c5674b0.js:1:73235)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
(anonymous) @ index-7c5674b0.js:5
index-7c5674b0.js:5  TypeError: Cannot read properties of undefined (reading '08631d6d-b2d8-4bf5-adbe-40daa23931ac_41049')
    at Devices.getDevice (index-7c5674b0.js:114:458208)
    at Devices.get (index-7c5674b0.js:114:458143)
    at watch.immediate (index-7c5674b0.js:1661:10308)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at callWithAsyncErrorHandling (index-7c5674b0.js:1:21719)
    at H (index-7c5674b0.js:1:36079)
    at doWatch (index-7c5674b0.js:1:36387)
    at watch (index-7c5674b0.js:1:34937)
    at setup (index-7c5674b0.js:1661:9173)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at setupStatefulComponent (index-7c5674b0.js:1:90664)
    at setupComponent (index-7c5674b0.js:1:90317)
    at ae (index-7c5674b0.js:1:73235)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
(anonymous) @ index-7c5674b0.js:5
index-7c5674b0.js:5  TypeError: Cannot read properties of undefined (reading '08631d6d-b2d8-4bf5-adbe-40daa23931ac')
    at Devices.getDevice (index-7c5674b0.js:114:458208)
    at Devices.get (index-7c5674b0.js:114:458143)
    at watch.immediate (index-7c5674b0.js:1661:10308)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at callWithAsyncErrorHandling (index-7c5674b0.js:1:21719)
    at H (index-7c5674b0.js:1:36079)
    at doWatch (index-7c5674b0.js:1:36387)
    at watch (index-7c5674b0.js:1:34937)
    at setup (index-7c5674b0.js:1661:9173)
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at setupStatefulComponent (index-7c5674b0.js:1:90664)
    at setupComponent (index-7c5674b0.js:1:90317)
    at ae (index-7c5674b0.js:1:73235)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
    at re (index-7c5674b0.js:1:73071)
    at F (index-7c5674b0.js:1:69115)
    at J (index-7c5674b0.js:1:70937)
    at X (index-7c5674b0.js:1:70002)
    at q (index-7c5674b0.js:1:69778)
    at F (index-7c5674b0.js:1:69080)
    at ReactiveEffect.me [as fn] (index-7c5674b0.js:1:74602)
    at ReactiveEffect.run (index-7c5674b0.js:1:8447)
    at Ne.update (index-7c5674b0.js:1:75002)
    at ue (index-7c5674b0.js:1:75042)
    at ae (index-7c5674b0.js:1:73371)
(anonymous) @ index-7c5674b0.js:5
index-7c5674b0.js:5  TypeError: Cannot read properties of undefined (reading '2bebf121-d7ab-430e-aed6-9e02017b6a3f')
    at Devices.getDevice (index-7c5674b0.js:114:458208)
    at Devices.get (index-7c5674b0.js:114:458143)
    at index-7c5674b0.js:1903:96786
    at Proxy.forEach (<anonymous>)
    at Proxy.mounted (index-7c5674b0.js:1903:96736)
    at index-7c5674b0.js:1:47157
    at callWithErrorHandling (index-7c5674b0.js:1:21597)
    at callWithAsyncErrorHandling (index-7c5674b0.js:1:21719)
    at r.__weh.r.__weh (index-7c5674b0.js:1:46936)
    at flushPostFlushCbs (index-7c5674b0.js:1:23919)
    at flushJobs `

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.27` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.27` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
leider nicht
die liste ist immer noch leer.
in den Widgets scheinen sie als versteckt noch da zu sein.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/8c1aac07-030f-4b6d-b3f1-29bedc7eee85)
sonst würde er die Reihung wohl nicht anzeigen

**Comment by intruder7777** [comment]
strange, hab jetzt cookies und cache gelöscht und damit geht es wieder
