### ISSUE TITLE
Habe das Problem das öfters (1x pro Tag) Jarvis abstürzt

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#2582]
Habe das Problem, dass Jarvis sehr oft abstürzt. Interessanterweise nur in der Installation in der Firma (haben eine längerfristige Lizenz - eXXcellent solutions). Privat haben wir das Problem nie.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/61848539/edd245e2-872a-473b-b964-0023cb449fbc)

```
<html>
<body>
<!--StartFragment--><pre class="markdown-highlight" style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: 13px; display: block; padding: 9.5px; margin: 1rem 0px 10px; line-height: 1.42857; word-break: break-all; overflow-wrap: break-word; color: rgb(51, 51, 51); background-color: rgb(255, 255, 255); border: none; border-radius: 0px; max-height: 350px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="hljs javascript" data-lines="1" style="box-sizing: border-box; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: inherit; padding: 0.5em; color: rgb(230, 225, 220); background: rgb(35, 35, 35); border-radius: 0px; white-space: pre; display: inline-block; overflow-x: auto; user-select: all; overflow-wrap: normal; min-width: 100%;">
  | 2024-01-28 10:17:25.369  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
-- | --
  | 2024-01-28 10:17:25.845  - [33mwarn[39m: jarvis.0 (157473) Install/InstallWizard.aspx: Not exists
  | 2024-01-28 10:17:25.851  - [33mwarn[39m: jarvis.0 (157473) opennms/login.jsp: Not exists
  | 2024-01-28 10:17:25.863  - [33mwarn[39m: jarvis.0 (157473) DesktopModules/AuthenticationServices/OpenID/license.txt: Not exists
  | 2024-01-28 10:17:25.875  - [33mwarn[39m: jarvis.0 (157473) login.jsp: Not exists
  | 2024-01-28 10:17:25.897  - [33mwarn[39m: jarvis.0 (157473) assets/login.jsp: Not exists
  | 2024-01-28 10:17:25.904  - [33mwarn[39m: jarvis.0 (157473) dotnetduke/default.aspx: Not exists
  | 2024-01-28 10:17:25.951  - [33mwarn[39m: jarvis.0 (157473) dotnetduke/Install/InstallWizard.aspx: Not exists
  | 2024-01-28 10:17:25.972  - [33mwarn[39m: jarvis.0 (157473) dotnetduke/DesktopModules/AuthenticationServices/OpenID/license.txt: Not exists
  | 2024-01-28 10:17:26.001  - [33mwarn[39m: jarvis.0 (157473) dotnetduke/: Not exists
  | 2024-01-28 10:17:26.042  - [33mwarn[39m: jarvis.0 (157473) dnnarticle/default.aspx: Not exists
  | 2024-01-28 10:17:26.076  - [33mwarn[39m: jarvis.0 (157473) dnnarticle/Install/InstallWizard.aspx: Not exists
  | 2024-01-28 10:17:26.095  - [33mwarn[39m: jarvis.0 (157473) dnnarticle/DesktopModules/AuthenticationServices/OpenID/license.txt: Not exists
  | 2024-01-28 10:17:26.139  - [33mwarn[39m: jarvis.0 (157473) dnnarticle/: Not exists
  | 2024-01-28 10:17:26.159  - [33mwarn[39m: jarvis.0 (157473) cms/default.aspx: Not exists
  | 2024-01-28 10:17:26.191  - [33mwarn[39m: jarvis.0 (157473) cms/Install/InstallWizard.aspx: Not exists
  | 2024-01-28 10:17:26.217  - [33mwarn[39m: jarvis.0 (157473) cms/DesktopModules/AuthenticationServices/OpenID/license.txt: Not exists
  | 2024-01-28 10:17:26.251  - [33mwarn[39m: jarvis.0 (157473) cms/: Not exists
  | 2024-01-28 10:17:26.280  - [33mwarn[39m: jarvis.0 (157473) DotNetNuke/default.aspx: Not exists
  | 2024-01-28 10:17:26.312  - [33mwarn[39m: jarvis.0 (157473) DotNetNuke/Install/InstallWizard.aspx: Not exists
  | 2024-01-28 10:17:26.344  - [33mwarn[39m: jarvis.0 (157473) DotNetNuke/DesktopModules/AuthenticationServices/OpenID/license.txt: Not exists
  | 2024-01-28 10:17:26.370  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:26.378  - [33mwarn[39m: hm-rpc.0 (264) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:26.393  - [33mwarn[39m: jarvis.0 (157473) DotNetNuke/: Not exists
  | 2024-01-28 10:17:26.425  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:26.426  - [33mwarn[39m: hm-rpc.0 (264) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:26.459  - [33mwarn[39m: hm-rpc.0 (264) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:26.523  - [33mwarn[39m: jarvis.0 (157473) Install/InstallWizard.aspx: Not exists
  | 2024-01-28 10:17:26.546  - [33mwarn[39m: jarvis.0 (157473) DesktopModules/AuthenticationServices/OpenID/license.txt: Not exists
  | 2024-01-28 10:17:26.587  - [33mwarn[39m: jarvis.0 (157473) assets/Install/InstallWizard.aspx: Not exists
  | 2024-01-28 10:17:26.619  - [33mwarn[39m: jarvis.0 (157473) assets/DesktopModules/AuthenticationServices/OpenID/license.txt: Not exists
  | 2024-01-28 10:17:26.709  - [33mwarn[39m: jarvis.0 (157473) index.php: Not exists
  | 2024-01-28 10:17:26.716  - [33mwarn[39m: host.iobroker-Server Cannot read file jarvis / assets/: EISDIR: illegal operation on a directory, read
  | 2024-01-28 10:17:26.750  - [31merror[39m: jarvis.0 (157473) uncaught exception: Cannot read properties of null (reading 'message')
  | 2024-01-28 10:17:26.751  - [31merror[39m: jarvis.0 (157473) TypeError: Cannot read properties of null (reading 'message')
  | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:11860)
  | at process.processImmediate (node:internal/timers:478:21)
  | 2024-01-28 10:17:26.751  - [31merror[39m: jarvis.0 (157473) Cannot read properties of null (reading 'message')
  | 2024-01-28 10:17:26.754  - [33mwarn[39m: jarvis.0 (157473) Terminated (UNCAUGHT_EXCEPTION): Without reason
  | 2024-01-28 10:17:26.772  - [33mwarn[39m: jarvis.0 (157473) admin/index.php: Not exists
  | 2024-01-28 10:17:26.834  - [33mwarn[39m: jarvis.0 (157473) : Not exists
  | 2024-01-28 10:17:26.883  - [33mwarn[39m: jarvis.0 (157473) index.php: Not exists
  | 2024-01-28 10:17:26.899  - [33mwarn[39m: jarvis.0 (157473) login.php: Not exists
  | 2024-01-28 10:17:26.926  - [33mwarn[39m: host.iobroker-Server Cannot read file jarvis / assets/: EISDIR: illegal operation on a directory, read
  | 2024-01-28 10:17:26.927  - [31merror[39m: jarvis.0 (157473) uncaught exception: Cannot read properties of null (reading 'message')
  | 2024-01-28 10:17:26.928  - [31merror[39m: jarvis.0 (157473) TypeError: Cannot read properties of null (reading 'message')
  | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:11860)
  | at process.processImmediate (node:internal/timers:478:21)
  | 2024-01-28 10:17:26.928  - [31merror[39m: jarvis.0 (157473) Cannot read properties of null (reading 'message')
  | 2024-01-28 10:17:26.947  - [33mwarn[39m: hm-rpc.0 (264) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:26.966  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:26.999  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:27.023  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:27.050  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:27.066  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:27.097  - [33mwarn[39m: hm-rpc.1 (294) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:27.217  - [33mwarn[39m: jarvis.0 (157473) trackit/Account/LogIn: Not exists
  | 2024-01-28 10:17:27.226  - [33mwarn[39m: jarvis.0 (157473) TrackIt/Account/LogIn: Not exists
  | 2024-01-28 10:17:27.233  - [33mwarn[39m: jarvis.0 (157473) TrackIT/Account/LogIn: Not exists
  | 2024-01-28 10:17:27.243  - [33mwarn[39m: jarvis.0 (157473) TrackItWeb/Account/LogIn: Not exists
  | 2024-01-28 10:17:27.248  - [33mwarn[39m: jarvis.0 (157473) tiweb/Account/LogIn: Not exists
  | 2024-01-28 10:17:27.260  - [33mwarn[39m: jarvis.0 (157473) Account/LogIn: Not exists
  | 2024-01-28 10:17:27.307  - [31merror[39m: host.iobroker instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
  | 2024-01-28 10:17:27.307  - [32minfo[39m: host.iobroker Restart adapter system.adapter.jarvis.0 because enabled
  | 2024-01-28 10:17:27.307  - [33mwarn[39m: host.iobroker Do not restart adapter system.adapter.jarvis.0 because restart loop detected
  | 2024-01-28 10:17:28.202  - [33mwarn[39m: hm-rpc.0 (264) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:28.229  - [33mwarn[39m: hm-rpc.0 (264) xmlrpc <- undefined method undefined with parameters undefined
  | 2024-01-28 10:17:28.246  - [33mwarn[39m: hm-rpc.0 (264) xmlrpc <- undefined method undefined with parameters undefined

</code></pre><!--EndFragment-->
</body>
</html>
```

**Comment by mcuiobroker** [comment]
Version angeben.

**Comment by Zefau** [comment]
@uwe72 seid ihr auf v3.1 oder v3.0 ?

**Comment by uwe72** [comment]
Melde mich heute. Grüße

Zefau ***@***.***> schrieb am Mo., 29. Jan. 2024, 22:56:

**Comment by uwe72** [comment]
v3.1.8

![image](https://github.com/Zefau/ioBroker.jarvis/assets/61848539/c09dca90-bab0-4cc9-a5d2-bc919334a59e)

**Comment by Hohenbostler** [comment]
Ich hänge mich hier mal ran. Auf meinem Tablet habe ich das Problem auch . iObroker sagt sagt das jarvis immer wieder für abbrüche sorgt. Im log steht folgendes.
Version bei mir ist die : 3.2.0-alpha.57
![image](https://github.com/Zefau/ioBroker.jarvis/assets/42488069/0d8bd6ae-bebe-4392-8e05-524ef9377ff6)

**Comment by Hohenbostler** [comment]
{
   "version": 3.2,
   "signature": 5724361492509430,
   "styles": "/*################################################################*/  /*#######################         Hintergrund             #######################*/  /*###############################################################*/  .jarvis-page-container { \tbackground-color: #0cbaba; \tbackground-image: linear-gradient(315deg, #0cbaba 0%, #380036 74%); }  .body--dark .jarvis-header { \tbackground-color: rgba(0,0,0,0.2) !important; }  .jarvis-tabs-container { \tbackground-color: rgba(0,0,0,0.2) !important; }  .jarvis-widget-container { \tbackground-color: rgba(0,0,0,0.2) !important; }  .body--dark .jarvis-widget { \tbackground: rgba(0,0,0,0.2); }  .body--light .jarvis-widget { \tbackground: rgba(255,255,255,1); }  .body--dark .jarvis-tabs-container { \tbackground-color: rgba(0,0,0,0.2) !important; }  .q-table__container { \tbackground-color: transparent !important; }  .jarvis-header { \tdisplay: none !important; }/*###########/*################################################################*/  /*################      Ab hier  beginnt der Feste Teil    ########################*/  /*###############################################################*/  /*################################################################*/  /*################      Vorschaltseite Buttons           ########################*/  /*###############################################################*/  /* Lichter*/  .jarvis-widget-7845d9ef-e7c1-460f-8ecf-609e0ae0f78d .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-7845d9ef-e7c1-460f-8ecf-609e0ae0f78d .jarvis-widget-content { \tbackground: url('https://api.iconify.design/line-md/lightbulb.svg') no-repeat center center / contain; \tbackground-color: orange !important; }  /* Rollos */  .jarvis-widget-37367ee7-50f3-4d48-bcd0-31804f564754 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-37367ee7-50f3-4d48-bcd0-31804f564754 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/mdi/window-shutter-cog.svg') no-repeat center center / contain; \tbackground-color: Grey !important; \ttext-align: center; }  /* Hauptinfo */  .jarvis-widget-690efabd-5821-4ab0-a533-ffd6c95ad5cf .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-690efabd-5821-4ab0-a533-ffd6c95ad5cf .jarvis-widget-content { \tbackground: url('https://api.iconify.design/ph/info-bold.svg') no-repeat center center / contain; \tbackground-color: lightBlue !important; \ttext-align: center; }  /* Walle */  .jarvis-widget-448081cd-646b-48f6-a572-b4bfb2da5f2d .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-448081cd-646b-48f6-a572-b4bfb2da5f2d .jarvis-widget-content { \tbackground: url('https://api.iconify.design/solar/smart-vacuum-cleaner-2-bold.svg') no-repeat center center / contain; \tbackground-color: lightGreen !important; \ttext-align: center; }  /*Verbraucher */  .jarvis-widget-18464e87-45a6-48f1-8bcd-8d8d56cf94c2 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-18464e87-45a6-48f1-8bcd-8d8d56cf94c2 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/material-symbols/electric-bolt-rounded.svg') no-repeat center center / contain; \tbackground-color: lightYellow !important; \ttext-align: center; }  /*Heizung */  .jarvis-widget-152a14a4-304c-4f16-a09b-0e36fbad94d2 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-152a14a4-304c-4f16-a09b-0e36fbad94d2 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/material-symbols/mode-heat-rounded.svg') no-repeat center center / contain; \tbackground-color: #E6676B !important; \ttext-align: center; }  /*Nuki*/  .jarvis-widget-1aed4adf-fbc5-46e5-bbb9-719383e1bd4c .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-1aed4adf-fbc5-46e5-bbb9-719383e1bd4c .jarvis-widget-content { \tbackground: url('https://api.iconify.design/material-symbols/lock.svg') no-repeat center center / contain; \tbackground-color: red !important; \ttext-align: center; }  /*Nuki aufschliessen*/  .jarvis-widget-ba59dabb-ff20-48cb-8da2-2637c7ab7f39 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-ba59dabb-ff20-48cb-8da2-2637c7ab7f39 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/mdi/unlocked.svg') no-repeat center center / contain; \tbackground-color: orange !important; \ttext-align: center; }  /* Energiefluss */  .jarvis-widget-f6182f4a-126d-4c61-8cc1-767afa7c55e1 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-f6182f4a-126d-4c61-8cc1-767afa7c55e1 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/mdi/house-city.svg') no-repeat center center / contain; \tbackground-color: lightgrey !important; \ttext-align: center; }  /*################################################################*/  /*################      Ausblenden auf dem Handy        ########################*/  /*###############################################################*/  @media all and (max-width:500px) { \t/* gilt für alle mit <= 500px max-width */  \t.jarvis-widget-6fcec8b4-2718-4848-b5e4-cb8c97856d8b { \t\tdisplay: none !important; \t}  \t.jarvis-widget-642e6745-8b6b-4c61-bc91-7b9f391ceb7f { \t\tdisplay: none !important; \t}  \t.jarvis-widget-1aed4adf-fbc5-46e5-bbb9-719383e1bd4c { \t\tdisplay: none !important; \t}  \t.jarvis-widget-ba59dabb-ff20-48cb-8da2-2637c7ab7f39 { \t\tdisplay: none !important; \t}  \t.jarvis-widget-f6182f4a-126d-4c61-8cc1-767afa7c55e1 { \t\tdisplay: none !important; \t} }  .body--dark .tile { \tborder-bottom: 0px solid transparent !important; }  .body--dark .tile { \tborder-right: 0px solid transparent !important; }  /*################################################################*/  /*############         Uhr und Datum angepasst             ########################*/  /*###############################################################*/  /* Große Uhr */  .jarvis-widget-2586215f-ce78-4234-9773-bafa30b6d772 .jarvis-DateTime-Clock-Date { \tfont-size: 100px; \tcolor: white; }  .jarvis-widget-642e6745-8b6b-4c61-bc91-7b9f391ceb7f .jarvis-DateTime-Clock-Time { \tfont-size: 130px; \tcolor: white; }  .jarvis-widget-6fcec8b4-2718-4848-b5e4-cb8c97856d8b .jarvis-DateTime-Clock-Date { \tfont-size: 40px; \tcolor: white; }  .jarvis-widget-20f7ee71-0350-4588-be09-e77a273e9c65 .jarvis-DateTime-Clock-Time { \tfont-size: 40px; \tcolor: white; }  /*################################################################*/  /*##########         Rundungen auf der Hauptseite        ########################*/  /*###############################################################*/  .jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-container { \tborder-radius: 30px; }  .jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-module-HomeKitTile { \tborder-radius: 30px; }  .jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-module-StateHTML { \tborder-radius: 30px; }  .jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-module-DateTime { \tborder-radius: 30px; }  .jarvis-tab-00754651-.jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-module-DateTime { \tborder-radius: 30px; } /*################################################################*/  /*##########         Hintergrund ausblenden       ########################*/  /*###############################################################*/  .jarvis-widget-container .jarvis-widget-c4345658-2537-468e-8d81-a800c4050bcd, .body--dark .bgcolor, .body--dark .paper { \tbackground-color: transparent !important; \tborder: 0px; }#####################################################*/  /*################      Ab hier  beginnt der Feste Teil    ########################*/  /*###############################################################*/  /*################################################################*/  /*################      Vorschaltseite Buttons           ########################*/  /*###############################################################*/  /* Lichter*/  .jarvis-widget-7845d9ef-e7c1-460f-8ecf-609e0ae0f78d .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-7845d9ef-e7c1-460f-8ecf-609e0ae0f78d .jarvis-widget-content { \tbackground: url('https://api.iconify.design/line-md/lightbulb.svg') no-repeat center center / contain; \tbackground-color: orange !important; }  /* Rollos */  .jarvis-widget-37367ee7-50f3-4d48-bcd0-31804f564754 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-37367ee7-50f3-4d48-bcd0-31804f564754 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/mdi/window-shutter-cog.svg') no-repeat center center / contain; \tbackground-color: Grey !important; \ttext-align: center; }  /* Hauptinfo */  .jarvis-widget-690efabd-5821-4ab0-a533-ffd6c95ad5cf .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-690efabd-5821-4ab0-a533-ffd6c95ad5cf .jarvis-widget-content { \tbackground: url('https://api.iconify.design/ph/info-bold.svg') no-repeat center center / contain; \tbackground-color: lightBlue !important; \ttext-align: center; }  /* Walle */  .jarvis-widget-448081cd-646b-48f6-a572-b4bfb2da5f2d .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-448081cd-646b-48f6-a572-b4bfb2da5f2d .jarvis-widget-content { \tbackground: url('https://api.iconify.design/solar/smart-vacuum-cleaner-2-bold.svg') no-repeat center center / contain; \tbackground-color: lightGreen !important; \ttext-align: center; }  /*Verbraucher */  .jarvis-widget-18464e87-45a6-48f1-8bcd-8d8d56cf94c2 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-18464e87-45a6-48f1-8bcd-8d8d56cf94c2 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/material-symbols/electric-bolt-rounded.svg') no-repeat center center / contain; \tbackground-color: lightYellow !important; \ttext-align: center; }  /*Heizung */  .jarvis-widget-152a14a4-304c-4f16-a09b-0e36fbad94d2 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-152a14a4-304c-4f16-a09b-0e36fbad94d2 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/material-symbols/mode-heat-rounded.svg') no-repeat center center / contain; \tbackground-color: #E6676B !important; \ttext-align: center; }  /*Nuki*/  .jarvis-widget-1aed4adf-fbc5-46e5-bbb9-719383e1bd4c .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-1aed4adf-fbc5-46e5-bbb9-719383e1bd4c .jarvis-widget-content { \tbackground: url('https://api.iconify.design/material-symbols/lock.svg') no-repeat center center / contain; \tbackground-color: red !important; \ttext-align: center; }  /*Nuki aufschliessen*/  .jarvis-widget-ba59dabb-ff20-48cb-8da2-2637c7ab7f39 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-ba59dabb-ff20-48cb-8da2-2637c7ab7f39 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/mdi/unlocked.svg') no-repeat center center / contain; \tbackground-color: orange !important; \ttext-align: center; }  /*BKW schalten*/  .jarvis-widget-35d70e12-e076-48dd-ab45-75101057d8bc .jarvis-widget-content { \tbackground-color: green !important; \ttext-align: left; }  /* Energiefluss */  .jarvis-widget-f6182f4a-126d-4c61-8cc1-767afa7c55e1 .jarvis-widget-header { \ttext-align: center; }  .jarvis-widget-f6182f4a-126d-4c61-8cc1-767afa7c55e1 .jarvis-widget-content { \tbackground: url('https://api.iconify.design/mdi/house-city.svg') no-repeat center center / contain; \tbackground-color: lightgrey !important; \ttext-align: center; }  /*################################################################*/  /*################      Ausblenden auf dem Handy        ########################*/  /*###############################################################*/  @media all and (max-width:500px) { \t/* gilt für alle mit <= 500px max-width */  \t.jarvis-widget-6fcec8b4-2718-4848-b5e4-cb8c97856d8b { \t\tdisplay: none !important; \t}  \t.jarvis-widget-642e6745-8b6b-4c61-bc91-7b9f391ceb7f { \t\tdisplay: none !important; \t}  \t.jarvis-widget-1aed4adf-fbc5-46e5-bbb9-719383e1bd4c { \t\tdisplay: none !important; \t}  \t.jarvis-widget-ba59dabb-ff20-48cb-8da2-2637c7ab7f39 { \t\tdisplay: none !important; \t}  \t.jarvis-widget-f6182f4a-126d-4c61-8cc1-767afa7c55e1 { \t\tdisplay: none !important; \t} }  .body--dark .tile { \tborder-bottom: 0px solid transparent !important; }  .body--dark .tile { \tborder-right: 0px solid transparent !important; }  /*################################################################*/  /*############         Uhr und Datum angepasst             ########################*/  /*###############################################################*/  /* Große Uhr */  .jarvis-widget-2586215f-ce78-4234-9773-bafa30b6d772 .jarvis-DateTime-Clock-Date { \tfont-size: 100px; \tcolor: white; }  .jarvis-widget-642e6745-8b6b-4c61-bc91-7b9f391ceb7f .jarvis-DateTime-Clock-Time { \tfont-size: 130px; \tcolor: white; }  .jarvis-widget-6fcec8b4-2718-4848-b5e4-cb8c97856d8b .jarvis-DateTime-Clock-Date { \tfont-size: 40px; \tcolor: white; }  .jarvis-widget-20f7ee71-0350-4588-be09-e77a273e9c65 .jarvis-DateTime-Clock-Time { \tfont-size: 40px; \tcolor: white; }  /*################################################################*/  /*##########         Rundungen auf der Hauptseite        ########################*/  /*###############################################################*/  .jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-container { \tborder-radius: 30px; }  .jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-module-HomeKitTile { \tborder-radius: 30px; }  .jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-module-StateHTML { \tborder-radius: 30px; }  .jarvis-tab-00754651-6ed5-4f6d-a4c2-230e09971e10 .jarvis-widget-module-DateTime { \tborder-radius: 30px; }  /*################################################################*/  /*##########         Hintergrund ausblenden       ########################*/  /*###############################################################*/  .jarvis-widget-container .jarvis-widget-c4345658-2537-468e-8d81-a800c4050bcd, .body--dark .bgcolor, .body--dark .paper { \tbackground-color: transparent !important; \tborder: 0px; }"
}

**Comment by Zefau** [comment]
Das Zeichen `/` bzw. `//` ist kein valider Kommentar im CSS. Es muss immer `/* ... */` sein.

**Comment by Zefau** [comment]
@Hohenbostler @uwe72 kann das hier zu?
