### ISSUE TITLE
[v3.2.0-beta.19] Fehlermeldung nach automatischem Reconnect

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2675]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e51b405e-6086-4735-b140-3447a495ea3d)
```
"Error: Client is not authenticated!
    at JarvisServer.handleClientCommand (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.server.client.js:1:6978)
    at JarvisServer.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.server.js:1:2659)
    at JarvisServer.emit (node:events:519:28)
    at JarvisServer.handleClientEvent (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.server.client.js:1:6154)
    at JarvisClient.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.server.client.js:1:3068)
    at JarvisClient.emit (node:events:519:28)
    at JarvisClient.message (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.client.js:1:1156)
    at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.client.js:1:1112)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/opt/iobroker/node_modules/ws/lib/websocket.js:1209:20)"
```

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Nicht mehr aufgetaucht. Ich schließe es erstmal. Danke.
