### ISSUE TITLE
jarvis-scripts vor Update / Upgrade anlegen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2802]
Beim Upgrade von v3.1.8 auf v3.2.0.rc.X hat es mehrfach Probleme mit dem nicht vorhandenen Verzeichnis
`jarvis-scripts` gegeben. insofern sollte es vorab angelegt, wenn es nicht vorhanden ist.

**Comment by Zefau** [comment]
Im Release Candidate wird es bereits angelegt.

**Comment by mcuiobroker** [comment]
Die User haben auf v3.2.0-rc.3 upgegradet und einen Fehler erhalten.
```
	2024-09-14 16:35:51.756	error	Exception-Code: ENOENT: ENOENT: no such file or directory, stat '/opt/iobroker/iobroker-data/files/0_userdata.0/jarvis-scripts'
 
jarvis.0
2024-09-14 16:35:51.754	error	Error: ENOENT: no such file or directory, stat '/opt/iobroker/iobroker-data/files/0_userdata.0/jarvis-scripts' at Object.statSync (node:fs:1665:25) at [kFSWatchStart] (node:internal/fs/recursive_watch:204:37) at watch (node:fs:2488:36) at JarvisServer.init (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.server.js:1:2460) at /opt/iobroker/node_modules/iobroker.jarvis/jarvis.min.js:1:2672
 
jarvis.0
2024-09-14 16:35:51.752	error	unhandled promise rejection: ENOENT: no such file or directory, stat '/opt/iobroker/iobroker-data/files/0_userdata.0/jarvis-scripts'
 
jarvis.0
2024-09-14 16:35:51.751	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

```

https://forum.iobroker.net/topic/68566/jarvis-v3-2-x-just-another-remarkable-vis/288?_=1726256267688

**Comment by Zefau** [comment]
Jo, das stimmt, das ist dann mit `rc-4` gefixed. Liegt daran, dass ich die Ordner überwache und die Erstellung des Ordners asynchron ist, also der Ordner noch nicht angelegt ist, wenn ich die Überwachung starte.

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.4` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.4` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Der Ordner wird nicht automatisch angelegt.
https://forum.iobroker.net/topic/68566/jarvis-v3-2-x-just-another-remarkable-vis/371 und ff
