### ISSUE TITLE
i18n # Word "....." not found in language de!

### ISSUE THREAD

**Issue by cryptedx** [Zefau/ioBroker.jarvis#447]
**Prerequisites**
- [yes] Are you on the latest stable or latest beta of jarvis?
- [ ] Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Versions**
- Which jarvis version are you running: 2.1.0 beta 4

**Describe the bug**
This is running the whole time in background when jarvis is open and I am clicking nothing. This wastes unnecessary resources. Also my words are already in German, there is nothing to translate.

![image](https://user-images.githubusercontent.com/20707078/102007474-a5d3b280-3d29-11eb-9107-81a43df252b2.png)

![image](https://user-images.githubusercontent.com/20707078/102007328-5b056b00-3d28-11eb-97e9-8c2a0862146d.png)

**Expected behavior**
Optimize it that no unnecessary resources aren't eaten up.

**Comment by Zefau** [comment]
@cryptedx Log reduced with `v2.1.0-beta.6`. Please test and confirm, thanks.

**Comment by cryptedx** [comment]
Hm, now I am getting a blank screen...

```
Log.js:56 App # Welcome to jarvis 2.1.0-beta.8
Log.js:56 App # You are on instance jarvis.0.
Connection.js:58 Connecting to http://192.168.1.21:8082 ..
Connection.js:62 Connected to http://192.168.1.21:8082.
Log.js:56 Settings # Set settings {_isSmallScreen: false, _isMobile: undefined, _isTablet: undefined, pageTitle: "HeartOfMyHome", themeDarkMode: true, …}
Log.js:56 Settings # Set layout [{…}]
Log.js:56 Settings # Set settings {_isSmallScreen: false, _isMobile: undefined, _isTablet: undefined, pageTitle: "HeartOfMyHome", themeDarkMode: true, …}
DevTools failed to load SourceMap: Could not load content for chrome-extension://cooahmcpmajfpnanjkdfiejkffphknnm/highlit.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
Log.js:56 App # Processed 139 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  {devices: {…}, states: Array(375), processedDevices: 139, addedDevices: 139, ignoredDevices: 0, …}
Log.js:56 App # Connected: true
Log.js:56 Connection # Connection closed!
Log.js:56 Connection # io client disconnect
value @ Log.js:56
a @ App.js:142
s.emit @ events.js:153
(anonymous) @ Socket.js:43
a.emit @ index.js:145
h.emit @ socket.js:138
h.onclose @ socket.js:214
h.close.h.disconnect @ socket.js:409
value @ Socket.js:129
value @ App.js:74
(anonymous) @ react-dom.production.min.js:209
os @ react-dom.production.min.js:214
ds @ react-dom.production.min.js:221
hu @ react-dom.production.min.js:253
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Ur @ react-dom.production.min.js:123
qr @ react-dom.production.min.js:122
Gs @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(anonymous) @ App.js:270
Promise.then (async)
(anonymous) @ App.js:268
Promise.then (async)
(anonymous) @ App.js:261
(anonymous) @ App.js:259
Promise.then (async)
value @ App.js:128
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
Gs @ react-dom.production.min.js:230
Nu @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tu @ react-dom.production.min.js:240
Bu @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
(anonymous) @ index.js:8
i @ index.html:1
(anonymous) @ main.2f7dce66.chunk.js:1
i @ index.html:1
r @ index.html:1
t @ index.html:1
(anonymous) @ main.2f7dce66.chunk.js:1
2react-dom.production.min.js:209 TypeError: Cannot read property 'val' of null
    at StateList.js:66
    at StateList.js:79
    at Vi (react-dom.production.min.js:153)
    at gs (react-dom.production.min.js:261)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Br (react-dom.production.min.js:122)
es @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
ci @ react-dom.production.min.js:131
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Ur @ react-dom.production.min.js:123
qr @ react-dom.production.min.js:122
Gs @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(anonymous) @ App.js:270
Promise.then (async)
(anonymous) @ App.js:268
Promise.then (async)
(anonymous) @ App.js:261
(anonymous) @ App.js:259
Promise.then (async)
value @ App.js:128
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
Gs @ react-dom.production.min.js:230
Nu @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tu @ react-dom.production.min.js:240
Bu @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
(anonymous) @ index.js:8
i @ index.html:1
(anonymous) @ main.2f7dce66.chunk.js:1
i @ index.html:1
r @ index.html:1
t @ index.html:1
(anonymous) @ main.2f7dce66.chunk.js:1
StateList.js:66 Uncaught (in promise) TypeError: Cannot read property 'val' of null
    at StateList.js:66
    at StateList.js:79
    at Vi (react-dom.production.min.js:153)
    at gs (react-dom.production.min.js:261)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Br (react-dom.production.min.js:122)
(anonymous) @ StateList.js:66
(anonymous) @ StateList.js:79
Vi @ react-dom.production.min.js:153
gs @ react-dom.production.min.js:261
lu @ react-dom.production.min.js:246
su @ react-dom.production.min.js:246
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Ur @ react-dom.production.min.js:123
qr @ react-dom.production.min.js:122
Gs @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(anonymous) @ App.js:270
Promise.then (async)
(anonymous) @ App.js:268
Promise.then (async)
(anonymous) @ App.js:261
(anonymous) @ App.js:259
Promise.then (async)
value @ App.js:128
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
Gs @ react-dom.production.min.js:230
Nu @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tu @ react-dom.production.min.js:240
Bu @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
(anonymous) @ index.js:8
i @ index.html:1
(anonymous) @ main.2f7dce66.chunk.js:1
i @ index.html:1
r @ index.html:1
t @ index.html:1
(anonymous) @ main.2f7dce66.chunk.js:1

**Comment by cryptedx** [comment]
Wie komme ich wieder auf die beta 7? Kann Jarvis gerade überhaupt nicht nutzen @Zefau

**Comment by Zefau** [comment]
hab dir mal die `v2.1.0-beta.9` freigegeben. Damit sollte der Bug behoben sein.

**Comment by cryptedx** [comment]
Nope leider immer noch nicht

**Comment by Zefau** [comment]
Selber Fehler?

**Comment by cryptedx** [comment]
Schau du mal:

https://gist.github.com/cryptedx/e401f2e94d6d2fe021103d14026a7648

**Comment by Zefau** [comment]
Installier bitte nochmal drüber und versuch nochmal.

**Comment by cryptedx** [comment]
Jetzt geht es aber es wird nichts mehr angezeigt. Nur die leereb Tabs und Gruppen. Im Hintergrund ist aber noch alles vorhanden. Also nichts gelöscht.

**Comment by Zefau** [comment]
Fehler im Log?

**Comment by cryptedx** [comment]
Log.js:56 App # Welcome to jarvis 2.1.0-beta.9
Log.js:56 App # You are on instance jarvis.0.
Connection.js:58 Connecting to http://192.168.1.21:8082 ..
Connection.js:62 Connected to http://192.168.1.21:8082.
Log.js:56 Settings # Set settings Object
Log.js:56 Settings # Set layout Array(1)
Log.js:56 Settings # Set settings Object
Log.js:56 App # Processed 139 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  Object
Log.js:56 App # Connected: true
index.html:1 Failed to decode downloaded font: http://192.168.1.21:8082/jarvis/fonts/materialdesignicons-webfont.woff2?v=5.8.55
index.html:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
index.html:1 Failed to decode downloaded font: http://192.168.1.21:8082/jarvis/fonts/materialdesignicons-webfont.woff2?v=5.8.55
index.html:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
DevTools failed to load SourceMap: Could not load content for chrome-extension://cooahmcpmajfpnanjkdfiejkffphknnm/highlit.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Zefau** [comment]
sorry dafür. 100x probieren nervt, aber irgendwie kann ich's nicht nachstellen. Installier' bitte nochmal drüber und versuch nochmal. Danke für die Geduld.

**Comment by cryptedx** [comment]
Alles gut, ich helfe gerne!

Log.js:56 App # Welcome to jarvis 2.1.0-beta.9
Log.js:56 App # You are on instance jarvis.0.
Connection.js:58 Connecting to http://192.168.1.21:8082 ..
Connection.js:62 Connected to http://192.168.1.21:8082.
Log.js:56 Settings # Set settings ObjectconfigExpertMode: falseconfigTab: "layout"pageTitle: "HeartOfMyHome"sendUsageData: falsethemeColorPrimary: ""themeDarkMode: truetoken: "edac1098aeb763a0956fb1bce0bfc4c0"_isMobile: undefined_isSmallScreen: false_isTablet: undefined__proto__: Object
Log.js:56 Settings # Set layout Array(1)0: {title: "", tabs: Array(12), id: "0", index: 0}length: 1__proto__: Array(0)
Log.js:56 Settings # Set settings ObjectconfigExpertMode: falseconfigTab: "layout"iobroker: {name: {…}, city: "Radolfzell", country: "Germany", longitude: "8.961861804127693", latitude: "47.74748134387943", …}pageTitle: "HeartOfMyHome"sendUsageData: falsethemeColorPrimary: ""themeDarkMode: truetoken: "edac1098aeb763a0956fb1bce0bfc4c0"_isMobile: undefined_isSmallScreen: false_isTablet: undefined__proto__: Object
Log.js:56 App # Processed 139 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  Object
Log.js:56 App # Connected: true
5Failed to decode downloaded font: <URL>
5OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
DevTools failed to load SourceMap: Could not load content for chrome-extension://cooahmcpmajfpnanjkdfiejkffphknnm/highlit.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Zefau** [comment]
Versuch mal `v2.1.0-beta.10`.

**Comment by cryptedx** [comment]
Ne, auch nicht...

Log.js:56 App # Welcome to jarvis 2.1.0-beta.10
Log.js:56 App # You are on instance jarvis.0.
Connection.js:58 Connecting to http://192.168.1.21:8082 ..
Connection.js:62 Connected to http://192.168.1.21:8082.
Log.js:56 Settings # Set settings Object
Log.js:56 Settings # Set settings Object
Log.js:56 Settings # Set layout Array(1)
Log.js:56 App # Processed 139 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  Object
Log.js:56 App # Connected: true
6Failed to decode downloaded font: <URL>
6OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
DevTools failed to load SourceMap: Could not load content for chrome-extension://cooahmcpmajfpnanjkdfiejkffphknnm/highlit.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by cryptedx** [comment]
Ich hab versuch ein Geräte zu einem Widget hinzuzufügen und es kommt derselbe Fehler!

```
Log.js:56 App # Welcome to jarvis 2.1.0-beta.10
Log.js:56 App # You are on instance jarvis.0.
Log.js:56 Connection # Connection URL (undefined) found in cache.
Connection.js:58 Connecting to http://192.168.1.21:8082 ..
Connection.js:62 Connected to http://192.168.1.21:8082.
Log.js:56 Settings # Set settings Object
Log.js:56 Settings # Set settings Object
Log.js:56 Settings # Set layout Array(1)
Log.js:56 App # Processed 139 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  Object
Log.js:56 App # Connected: true
21Failed to decode downloaded font: <URL>
21OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
react-dom.production.min.js:209 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ds (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2441875)
    at hu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2455116)
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at fu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2452974)
    at Qs (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2449105)
    at http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400291
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at Vr (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400236)
es @ react-dom.production.min.js:209
Log.js:56 Connection # Connection closed!
Log.js:56 Connection # io client disconnect
value @ Log.js:56
react-dom.production.min.js:209 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ds (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2441875)
    at hu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2455116)
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at fu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2452974)
    at Qs (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2449105)
    at http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400291
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at Vr (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400236)
es @ react-dom.production.min.js:209
react-dom.production.min.js:123 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ds (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2441875)
    at hu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2455116)
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at fu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2452974)
    at Qs (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2449105)
    at http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400291
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at Vr (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400236)
DevTools failed to load SourceMap: Could not load content for chrome-extension://cooahmcpmajfpnanjkdfiejkffphknnm/highlit.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/469

**Comment by cryptedx** [comment]
sieht gut aus mit dem logging.
