### ISSUE TITLE
Add device to widget fails

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#469]
_Originally posted by @cryptedx in https://github.com/Zefau/ioBroker.jarvis/issues/447#issuecomment-749412833_
> Ich hab versucht ein Geräte zu einem Widget hinzuzufügen und es kommt derselbe Fehler!

```
Log.js:56 App # Welcome to jarvis 2.1.0-beta.10
Log.js:56 App # You are on instance jarvis.0.
Log.js:56 Connection # Connection URL (undefined) found in cache.
Connection.js:58 Connecting to http://192.168.1.21:8082 ..
Connection.js:62 Connected to http://192.168.1.21:8082.
Log.js:56 Settings # Set settings Object
Log.js:56 Settings # Set settings Object
Log.js:56 Settings # Set layout Array(1)
Log.js:56 App # Processed 139 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  Object
Log.js:56 App # Connected: true
21Failed to decode downloaded font: <URL>
21OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
react-dom.production.min.js:209 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ds (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2441875)
    at hu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2455116)
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at fu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2452974)
    at Qs (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2449105)
    at http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400291
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at Vr (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400236)
es @ react-dom.production.min.js:209
Log.js:56 Connection # Connection closed!
Log.js:56 Connection # io client disconnect
value @ Log.js:56
react-dom.production.min.js:209 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ds (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2441875)
    at hu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2455116)
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at fu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2452974)
    at Qs (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2449105)
    at http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400291
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at Vr (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400236)
es @ react-dom.production.min.js:209
react-dom.production.min.js:123 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ds (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2441875)
    at hu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2455116)
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at fu (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2452974)
    at Qs (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2449105)
    at http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400291
    at t.unstable_runWithPriority (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2475873)
    at Br (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400000)
    at Vr (http://192.168.1.21:8082/jarvis/static/js/3.dec0729c.chunk.js:2:2400236)
DevTools failed to load SourceMap: Could not load content for chrome-extension://cooahmcpmajfpnanjkdfiejkffphknnm/highlit.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by cryptedx** [comment]
Warum machst du ein neues Issue auf, das hängt doch mit dem Problem davor zusammen und sollte kein neues sein?

**Comment by Zefau** [comment]
Das Issue war für unnötige i18n loggings. Jetzt kannst du keine Geräte in Widgets einfügen. Das hängt nicht zusammen.

**Comment by cryptedx** [comment]
Mir fehlen auch alle Geräte im Frontend seit du das i18n optimiert hast.

**Comment by Zefau** [comment]
Auch das hat nichts damit zu tun, dass ein einfaches Logging nicht mehr angezeigt wird.

Du meinst https://forum.iobroker.net/post/541418 ? Das sollte eigentlich mit `v2.1.0-beta.11` wieder passen? Geht das noch immer nicht? Kannst du mal den Cache leeren?

**Comment by cryptedx** [comment]
Ich muss ja erstmal wissen, das es eine beta 11 gibt ;-) Dachte du hast an der Stelle nicht weiter gemacht, weil nichts mehr kam. Ich sehe nun wieder alles. Geräte kann ich trotzdem nicht hinzufügen.

**Comment by Zefau** [comment]
Probier mal bitte die `v2.1.0-beta.12`.

**Comment by cryptedx** [comment]
Sobald ich auf "Szenen"
![image](https://user-images.githubusercontent.com/20707078/102887327-07e19580-4457-11eb-85a9-8119fa649fe6.png)

klicke krieg ich einen blank screen. Das war zuvor erst nachdem ich ein Gerät beim Hinzufügen angeklickt hatte.

```
react-dom.production.min.js:209 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BmoduleConfig%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ki (react-dom.production.min.js:139)
    at f (react-dom.production.min.js:143)
    at p (react-dom.production.min.js:145)
    at react-dom.production.min.js:149
    at To (react-dom.production.min.js:173)
    at gs (react-dom.production.min.js:262)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
es @ react-dom.production.min.js:209
i.componentDidCatch.n.callback @ react-dom.production.min.js:227
ci @ react-dom.production.min.js:131
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
Log.js:56 Connection # Connection closed!
Log.js:56 Connection # io client disconnect
value @ Log.js:56
a @ App.js:142
s.emit @ events.js:153
(anonymous) @ Socket.js:43
a.emit @ index.js:145
h.emit @ socket.js:138
h.onclose @ socket.js:214
h.close.h.disconnect @ socket.js:409
value @ Socket.js:129
value @ App.js:74
(anonymous) @ react-dom.production.min.js:209
os @ react-dom.production.min.js:214
ds @ react-dom.production.min.js:221
hu @ react-dom.production.min.js:253
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
react-dom.production.min.js:221 Failed to decode downloaded font: http://192.168.1.21:8082/jarvis/fonts/materialdesignicons-webfont.woff2?v=5.8.55
ds @ react-dom.production.min.js:221
hu @ react-dom.production.min.js:253
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
react-dom.production.min.js:221 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
ds @ react-dom.production.min.js:221
hu @ react-dom.production.min.js:253
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
react-dom.production.min.js:209 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BmoduleConfig%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ki (react-dom.production.min.js:139)
    at f (react-dom.production.min.js:143)
    at p (react-dom.production.min.js:145)
    at react-dom.production.min.js:149
    at To (react-dom.production.min.js:173)
    at gs (react-dom.production.min.js:262)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
es @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
ci @ react-dom.production.min.js:131
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
react-dom.production.min.js:209 Failed to decode downloaded font: http://192.168.1.21:8082/jarvis/fonts/materialdesignicons-webfont.woff2?v=5.8.55
es @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
ci @ react-dom.production.min.js:131
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
react-dom.production.min.js:209 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
es @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
ci @ react-dom.production.min.js:131
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
react-dom.production.min.js:139 Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BmoduleConfig%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ki (react-dom.production.min.js:139)
    at f (react-dom.production.min.js:143)
    at p (react-dom.production.min.js:145)
    at react-dom.production.min.js:149
    at To (react-dom.production.min.js:173)
    at gs (react-dom.production.min.js:262)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
ki @ react-dom.production.min.js:139
f @ react-dom.production.min.js:143
p @ react-dom.production.min.js:145
(anonymous) @ react-dom.production.min.js:149
To @ react-dom.production.min.js:173
gs @ react-dom.production.min.js:262
lu @ react-dom.production.min.js:246
su @ react-dom.production.min.js:246
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
[Violation] 'click' handler took 87653ms

**Comment by Zefau** [comment]
fixed with `v2.1.0-beta.13`.

**Comment by cryptedx** [comment]
Sauber läuft!

**Comment by cryptedx** [comment]
Es fängt wieder an bei mir:

![image](https://user-images.githubusercontent.com/20707078/109957869-d2beb280-7ce5-11eb-8a00-6145aae6fced.png)

**Comment by cryptedx** [comment]
Ich hab die letzte Zeit wenig an Jarvis machen können. Jetzt bin ich wieder aktiver und diese Fehler tritt sogar auf, wenn ich die Seite einfach nur offen habe. Manchmal auch wenn ich gerade etwas neues hinzufüge. Dann ist alles verloren, was ich zuvor neu konfiguriert habe. Ist halt schwer jeder Sekunden zu speichern. @Zefau

**Comment by cryptedx** [comment]
Schau dir das mal an. Beim Tippen in die Titel der Widget Box kommt der Fehler auch...

![Mar-07-2021 10-42-56](https://user-images.githubusercontent.com/20707078/110235736-f37b4800-7f31-11eb-9be8-7584389348ac.gif)
