### ISSUE TITLE
New installation - first start - Unknown error. With git version it has more details "TypeError: Cannot read property 'parentNode' of null"

### ISSUE THREAD

**Issue by PeterVoronov** [Zefau/ioBroker.jarvis#674]
New clean install of jarvis.

**Prerequisites / Voraussetzungen**
- [2.10 and after - 2.2.0-beta.48 ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
Error as described in Subject - clean install and nothing possible to do at all
**Screenshots**
There is an error message on main screen:
`jarvis crashed due to an error
Please screenshot the entire page and report to the developer (open a Github issue or post in the ioBroker forum)

TypeError: Cannot read property 'parentNode' of null
TypeError: Cannot read property 'parentNode' of null
    at http://iobroker:8082/jarvis/static/js/main.bc6b7725.chunk.js:1:302575
    at ts (http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1807709)
    at os (http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1809775)
    at cs (http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1811591)
    at hu (http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1825115)
    at t.unstable_runWithPriority (http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1845872)
    at Ha (http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1769999)
    at fu (http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1822973)
    at Qs (http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1819104)
    at http://iobroker:8082/jarvis/static/js/11.23f54cf8.chunk.js:2:1770290`

Another errors from the browser console:

App.js:84 TypeError: Cannot read property 'parentNode' of null
    at Widget.js:116
    at ts (react-dom.production.min.js:209)
    at os (react-dom.production.min.js:214)
    at cs (react-dom.production.min.js:220)
    at hu (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123 
{componentStack: "↵    in div↵    in ForwardRef↵    in ForwardRef↵  …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}
App.js:84 TypeError: Cannot read property 'parentNode' of null
    at Widget.js:116
    at ts (react-dom.production.min.js:209)
    at os (react-dom.production.min.js:214)
    at cs (react-dom.production.min.js:220)
    at hu (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123 
{componentStack: "↵    in div↵    in ForwardRef↵    in ForwardRef↵  …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}
App.js:84 TypeError: Cannot read property 'parentNode' of null
    at Widget.js:116
    at ts (react-dom.production.min.js:209)
    at os (react-dom.production.min.js:214)
    at cs (react-dom.production.min.js:220)
    at hu (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123 
{componentStack: "↵    in div↵    in ForwardRef↵    in ForwardRef↵  …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}
App.js:84 TypeError: Cannot read property 'parentNode' of null
    at Widget.js:116
    at ts (react-dom.production.min.js:209)
    at os (react-dom.production.min.js:214)
    at cs (react-dom.production.min.js:220)
    at hu (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123 
{componentStack: "↵    in div↵    in ForwardRef↵    in ForwardRef↵  …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}
App.js:84 TypeError: Cannot read property 'parentNode' of null
    at Widget.js:116
    at ts (react-dom.production.min.js:209)
    at os (react-dom.production.min.js:214)
    at cs (react-dom.production.min.js:220)
    at hu (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123 
{componentStack: "↵    in div↵    in ForwardRef↵    in ForwardRef↵  …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}
App.js:84 TypeError: Cannot read property 'parentNode' of null
    at Widget.js:116
    at ts (react-dom.production.min.js:209)
    at os (react-dom.production.min.js:214)
    at cs (react-dom.production.min.js:220)
    at hu (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123 
{componentStack: "↵    in div↵    in ForwardRef↵    in ForwardRef↵  …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}
App.js:84 TypeError: Cannot read property 'parentNode' of null
    at Widget.js:116
    at ts (react-dom.production.min.js:209)
    at os (react-dom.production.min.js:214)
    at cs (react-dom.production.min.js:220)
    at hu (react-dom.production.min.js:253)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at fu (react-dom.production.min.js:248)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123 
{componentStack: "↵    in div↵    in ForwardRef↵    in ForwardRef↵  …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}
﻿

**Comment by Zefau** [comment]
Please try with `v2.2.0-beta.49`.

**Comment by PeterVoronov** [comment]
Hi.

The TypeError: Cannot read property 'parentNode' of null is gone,

But still three other exists:

Main screen:

![image](https://user-images.githubusercontent.com/66964358/108751844-64425d80-754b-11eb-8eb9-adcfbc4c1015.png)

jarvis crashed due to an error
Please screenshot the entire page and report to the developer (open a Github issue or post in the ioBroker forum)

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _i (http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1780519)
    at http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1785407
    at To (http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1794889)
    at vs (http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1835417)
    at lu (http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1825926)
    at su (http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1825851)
    at Qs (http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1822860)
    at http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1774245
    at t.unstable_runWithPriority (http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1849827)
    at Ha (http://iot-main.catshome.name:8082/jarvis/static/js/11.fa295d47.chunk.js:2:1773954)


And from a console
App # Processed 19 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  {devices: {…}, states: Array(95), processedDevices: 19, addedDevices: 19, ignoredDevices: 0, …}
2react-dom.production.min.js:209 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _i (react-dom.production.min.js:139)
    at react-dom.production.min.js:149
    at To (react-dom.production.min.js:173)
    at vs (react-dom.production.min.js:265)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
es @ react-dom.production.min.js:209
n.payload @ react-dom.production.min.js:227
ci @ react-dom.production.min.js:129
Io @ react-dom.production.min.js:179
vs @ react-dom.production.min.js:263
lu @ react-dom.production.min.js:246
su @ react-dom.production.min.js:246
Qs @ react-dom.production.min.js:239
(анонимный) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ha @ react-dom.production.min.js:122
Xa @ react-dom.production.min.js:123
Va @ react-dom.production.min.js:122
Gs @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(анонимный) @ AdapterStatus.js:163
h.onack @ socket.js:319
h.onpacket @ socket.js:248
(анонимный) @ index.js:21
r.emit @ index.js:145
h.ondecoded @ manager.js:349
(анонимный) @ index.js:21
r.emit @ index.js:145
d.add @ index.js:251
h.ondata @ manager.js:339
(анонимный) @ index.js:21
r.emit @ index.js:145
c.onPacket @ socket.js:461
(анонимный) @ socket.js:278
r.emit @ index.js:145
i.onPacket @ transport.js:149
i.onData @ transport.js:141
ws.onmessage @ websocket.js:160
Показать еще кадры из кода библиотеки (4)
App.js:84 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _i (react-dom.production.min.js:139)
    at react-dom.production.min.js:149
    at To (react-dom.production.min.js:173)
    at vs (react-dom.production.min.js:265)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122) {componentStack: "↵    in span↵    in ForwardRef↵    in ForwardRef↵ …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}
value @ App.js:84
i.componentDidCatch.n.callback @ react-dom.production.min.js:227
di @ react-dom.production.min.js:131
is @ react-dom.production.min.js:212
hu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ha @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(анонимный) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ha @ react-dom.production.min.js:122
Xa @ react-dom.production.min.js:123
Va @ react-dom.production.min.js:122
Gs @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(анонимный) @ AdapterStatus.js:163
h.onack @ socket.js:319
h.onpacket @ socket.js:248
(анонимный) @ index.js:21
r.emit @ index.js:145
h.ondecoded @ manager.js:349
(анонимный) @ index.js:21
r.emit @ index.js:145
d.add @ index.js:251
h.ondata @ manager.js:339
(анонимный) @ index.js:21
r.emit @ index.js:145
c.onPacket @ socket.js:461
(анонимный) @ socket.js:278
r.emit @ index.js:145
i.onPacket @ transport.js:149
i.onData @ transport.js:141
ws.onmessage @ websocket.js:160
Показать еще кадры из кода библиотеки (5)
App.js:84 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _i (react-dom.production.min.js:139)
    at react-dom.production.min.js:149
    at To (react-dom.production.min.js:173)
    at vs (react-dom.production.min.js:265)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122) {componentStack: "↵    in span↵    in ForwardRef↵    in ForwardRef↵ …wardRef↵    in Unknown↵    in s↵    in ForwardRef"}

**Comment by Zefau** [comment]
Could you please delete the instance, restart jarvis, restart web and socket-io adapter und re-create the instance?

Does the error persist?

**Comment by PeterVoronov** [comment]
thanks you.
solved
