### ISSUE TITLE
Jarvis zeigt Fehler nach Installation im Zusammenhang mit JSONL Umstellung

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#678]
Hi...ich habe einen seltsamen Fehler nach dem Update von JARVIS auf 2.2.0, wobei der Update an sich keinen Fehler erzeugt hat.

```
2021-02-25 08:05:30.352 - info: host.MSNUC-IOB instance system.adapter.jarvis.0 started with pid 3993
2021-02-25 08:05:31.387 - error: host.MSNUC-IOB Caught by controller[0]: /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:428
2021-02-25 08:05:31.387 - error: host.MSNUC-IOB Caught by controller[0]: throw new Error(`Unknown states type: ${config.states.type}: ${err.message}`);
2021-02-25 08:05:31.388 - error: host.MSNUC-IOB Caught by controller[0]: ^
2021-02-25 08:05:31.388 - error: host.MSNUC-IOB Caught by controller[0]: Error: Unknown states type: jsonl: Cannot find module '@iobroker/db-states-jsonl'
2021-02-25 08:05:31.388 - error: host.MSNUC-IOB Caught by controller[0]: Require stack:
2021-02-25 08:05:31.388 - error: host.MSNUC-IOB Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js
2021-02-25 08:05:31.388 - error: host.MSNUC-IOB Caught by controller[0]: - /opt/iobroker/node_modules/@iobroker/adapter-core/build/utils.js
2021-02-25 08:05:31.388 - error: host.MSNUC-IOB Caught by controller[0]: - /opt/iobroker/node_modules/@iobroker/adapter-core/build/index.js
2021-02-25 08:05:31.389 - error: host.MSNUC-IOB Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.jarvis/jarvis.js
2021-02-25 08:05:31.389 - error: host.MSNUC-IOB Caught by controller[0]: at new Adapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:428:19)
2021-02-25 08:05:31.389 - error: host.MSNUC-IOB Caught by controller[0]: at startAdapter (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:69:12)
2021-02-25 08:05:31.389 - error: host.MSNUC-IOB Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:555:2)
2021-02-25 08:05:31.389 - error: host.MSNUC-IOB Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-02-25 08:05:31.389 - error: host.MSNUC-IOB Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-02-25 08:05:31.390 - error: host.MSNUC-IOB Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:928:32)
2021-02-25 08:05:31.390 - error: host.MSNUC-IOB Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-02-25 08:05:31.390 - error: host.MSNUC-IOB Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
2021-02-25 08:05:31.390 - error: host.MSNUC-IOB Caught by controller[0]: at internal/main/run_main_module.js:17:47
2021-02-25 08:05:31.390 - error: host.MSNUC-IOB instance system.adapter.jarvis.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-02-25 08:05:31.391 - info: host.MSNUC-IOB Restart adapter system.adapter.jarvis.0 because enabled
```
Ich habe mal versucht bei JARVIS einen Upload oder auch zu deinstallieren, bekomme aber dann:

```
$ ./iobroker upload jarvis
ERROR: Installation broken or unknown states type: jsonl configured.
ERROR: process exited with code 101

$ ./iobroker del jarvis
ERROR: Installation broken or unknown states type: jsonl configured.
ERROR: process exited with code 101
```
Hat jemand eine Idee?

**Comment by MarkSau** [comment]
Das Update hat meine komplette iobroker Installation kaputt gemacht. 
Iobroker wollte nicht mehr starten
ERROR: Installation broken or unknown states type: jsonl configured.
Habe das auch im Forum zu JSONL gepostet.
Bin jetzt wieder zurück auf Redis/File und dann funktioniert der Update auch..
Schon seltsam

**Comment by Zefau** [comment]
Ist kein jarvis spezifischer Fehler. JsonL ist eine neue Speicher Methodik von ioBroker und noch im beta Stadium meine ich.

**Comment by MarkSau** [comment]
ja, richtig...inzwischen auch festegestellt, das die Problematik nicht bei Jarvis liegt.
Danke übrigens nochmals für deinen super Job..
